login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.user_login, name='login'),
    #/restricted views
    url(r'^restricted/$', views.restricted, name='restricted'),
    #/logout
    url(r'^logout/$', views.user_logout, name='logout'),
    #change_password
    url(r'^change_password/$', views.change_password, name='change_password'),

]

manajemen/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    #HPD
    url(r'^hpd/$', views.home_hpd, name='home_hpd'),
    #/new_article
    url(r'^hpd/article/new/$', views.new_article, name='new_article'),
    #/article_detail
    url(r'^hpd/article/detail-(?P<article_id>[0-9]+)/$', views.detail_article, name='detail_article'),
    #/article_edit
    url(r'^hpd/article/detail-(?P<article_id>[0-9]+)/edit/$', views.edit_article, name='edit_article'),
    url(r'^hpd/main-article/detail-(?P<article_id>[0-9]+)/edit/$', views.edit_mainarticle, name='edit_mainarticle'),
    #/article_delete
    url(r'^hpd/delete_schedule/(?P<article_id>[0-9]+)/$', views.delete_article, name='delete_article'),
    #/edit_contact
    url(r'^hpd/contact/edit/$', views.edit_contact, name='edit_contact'),


    #psdm V
    url(r'^psdm/$', views.home_psdm, name='home_psdm'),
    #psdm V
    url(r'^psdm/user_move_kelas/(?P<user_id>[0-9]+)/$', views.move_class, name='move_class'),
    #/new_kelas
    url(r'^psdm/new_kelas/$', views.new_kelas, name='new_kelas'),
    #/new_schedule
    url(r'^psdm/new_schedule/$', views.new_schedule, name='new_schedule'),
    #/new_attendance_people
    url(r'^psdm/new_attendance_kelas/new_attendance_people/(?P<attendance_id>[0-9]+)$', views.new_attendance_people, name='new_attendance_people'),
    #/new_attendance_kelas
    url(r'^psdm/new_attendance_kelas/$', views.new_attendance_kelas, name='new_attendance_kelas'),
    #/edit_attendance
    url(r'^psdm/edit_attendance/(?P<attendance_id>[0-9]+)/$', views.edit_attendance, name='edit_attendance'),
    #/delete_attendance
    url(r'^psdm/delete_attendance/(?P<attendance_id>[0-9]+)/$', views.delete_attendance, name='delete_attendance'),

    #/schedule_edit
    url(r'^psdm/edit_schedule/(?P<schedule_id>[0-9]+)/$', views.edit_schedule, name='edit_schedule'),
    #/schedule_delete
    url(r'^psdm/delete_schedule/(?P<schedule_id>[0-9]+)/$', views.delete_schedule, name='delete_schedule'),

    #Keuangan
    url(r'^keuangan/$', views.home_bendahara, name='home_keuangan'),
    #keuangan_new_pembayaran
    url(r'^keuangan/new_pembayaran/$', views.new_pembayaran, name='new_pembayaran'),
    #confirmation_payments
    url(r'^keuangan/konfirmasi_pembayaran/(?P<payment_id>[0-9]+)/$', views.confirmation_payment, name='confirmation_payment'),
    #Cancel_payments
    url(r'^keuangan/gagalkan_pembayaran/(?P<payment_id>[0-9]+)/$', views.cancel_payment, name='cancel_payment'),
    #keuangan_new_tipe_pembayaran
    url(r'^keuangan/new_tipe_pembayaran/$', views.new_administration_type, name='new_administration_type'),
    #keuangan_edit_administration_type
    url(r'^keuangan/edit_tipe_pembayaran/(?P<payment_type_id>[0-9]+)/$', views.edit_administration_type, name='edit_administration_type'),

    #acara
    url(r'^acara/$', views.home_program, name='home_acara'),
    #acara_new_event
    url(r'^acara/new_event/$', views.new_event, name='new_event'),
    #acara_edit_event
    url(r'^acara/edit_event/(?P<event_id>[0-9]+)/$', views.edit_event, name='edit_event'),
    #acara_delete_event
    url(r'^acara/delete_(?P<event_id>[0-9]+)/$', views.delete_event, name='delete_event'),
    #confirmation_event
    url(r'^acara/konfirmasi_event/(?P<event_id>[0-9]+)/$', views.confirmation_event, name='confirmation_event'),
    #cancel event
    url(r'^acara/tolak_tawaran/(?P<event_id>[0-9]+)/$', views.cancel_event, name='cancel_event'),

    #Inventaris
    url(r'^inventaris/$', views.home_inventaris, name='home_inventaris'),
    #Inventaris_new_barang
    url(r'^inventaris/new_barang/$', views.new_barang, name='new_barang'),
    #inventaris_edit_barang
    url(r'^inventaris/edit_barang/(?P<barang_id>[0-9]+)/$', views.edit_barang, name='edit_barang'),
    #inventaris_delete_barang
    url(r'^inventaris/delete_(?P<barang_id>[0-9]+)/$', views.delete_barang, name='delete_barang'),

    #sekretaris
    url(r'^sekretaris/$', views.home_sekretaris, name='home_sekretaris'),
    #sekretaris-new meeting
    url(r'^sekretaris/new-meeting/$', views.new_meeting, name='new_meeting_note'),
    #sekretaris-edit meeting
    url(r'^sekretaris/edit_(?P<meeting_id>[0-9]+)/$', views.edit_meeting, name='edit_meeting'),
    #sekretaris-delete meeting
    url(r'^sekretaris/delete_(?P<meeting_id>[0-9]+)/$', views.delete_meeting, name='delete_meeting'),
    #sekretaris-deactivate_user
    url(r'^sekretaris/deactivate_(?P<user_id>[0-9]+)/$', views.deactivate_user, name='deactivate_user'),
    #sekretaris-activate_user
    url(r'^sekretaris/activate_(?P<user_id>[0-9]+)/$', views.activate_user, name='activate_user'),

]

manajemen/models.py
from django.db import models
from django.db.models import Sum
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

class Article(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=100)
    text = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to='images/articles')
    is_mainarticle = models.BooleanField(default = False)
    is_concertarticle = models.BooleanField(default= False)
    is_event = models.BooleanField(default= False)
    is_publish = models.BooleanField(default= False)
    created_date = models.DateTimeField(
        default = timezone.now
    )
    updated_date = models.DateTimeField(
        blank = True, null = True
    )
    published_date = models.DateTimeField(
        blank = True, null = True
    )
    class Meta:
        ordering =['-created_date',]
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def update(self):
        self.updated_date = timezone.now()
        self.save()
    def __str__(self):
        return self.title

class Practice(models.Model):
    date = models.DateTimeField(blank = False)
    place = models.CharField(max_length= 100)
    note = models.TextField()
    created_date = models.DateTimeField(
        default = timezone.now
        )
# class Meta:
#     ordering =['-date',]
# def __str__(self):
#     return "{} {}".format(self.date.date())

class Kelas(models.Model):
    nama_kelas = models.CharField(default='', max_length=50)
    note = models.TextField(null= True)
    updated_date = models.DateField(
        blank = True, null = True
    )
    def update(self):
        self.updated_date = timezone.now()
        self.save()

    class Meta:
        ordering =['-updated_date',]
    def __str__(self):
        return self.nama_kelas

class LogKelas(models.Model):
    kelas_current = models.ForeignKey(Kelas, related_name= 'log_kelas_current')
    user = models.ForeignKey(User, related_name='log_kelas_user')
    kelas_before = models.ForeignKey(Kelas, related_name='log_kelas_before', null=True)
    joined_date = models.DateTimeField(
        default = timezone.now
        )
    class Meta:
        ordering =['-joined_date',]

class PracticeAttendance(models.Model):
    kelas = models.ForeignKey(Kelas, related_name="practice_attendances", null=True)
    practice = models.ForeignKey(Practice, related_name= "practice_attendances")
    daftar_orang = models.ManyToManyField(User, related_name= "user_practice_attendances", blank=True)
    is_present = models.ManyToManyField(User, related_name= "practice_attendances", blank=True)
    tutor = models.ForeignKey(User, related_name= "tutor_practice_attendances", null=True)
    tutor_pendamping = models.ManyToManyField(User, related_name= "tutor_pendamping_practice_attendances", blank=True)
    updated_date = models.DateField(
        blank = True, null = True
    )
    def update(self):
        self.updated_date = timezone.now()
        self.save()
    class Meta:
        ordering =['-updated_date',]


class AdministrationType(models.Model):
    paymentstype = models.CharField(max_length = 50 )
    nominal = models.PositiveIntegerField()
    created_date = models.DateTimeField(
        default = timezone.now
    )
    updated_date = models.DateField(
    blank = True, null = True
    )
    def __str__(self):
        return self.paymentstype
    def update(self):
        self.updated_date = timezone.now()
        self.save()

class AdministrasiManager(models.Manager):
    def get_saldo(self):
        saldo = self.filter(status='paid').aggregate(Sum('nominal'))
        return saldo['nominal__sum']

class Administrasi(models.Model):
    method_choices= (
        ('cash','Cash',),
        ('transfer', 'Transfer',),
    )
    status_choices= (
        ('pending','Pending',),
        ('paid', 'Paid',),
        ('cancelled', 'Cancelled',),
    )
    user = models.ForeignKey(User, related_name="administrasi", null = True)
    jenis = models.ForeignKey(AdministrationType,related_name= "administrasi_jenis", null = True)
    nominal = models.PositiveIntegerField(null=True, blank=True)
    method = models.CharField(max_length=20, choices = method_choices, default= 'cash')
    image = models.ImageField(null=True, upload_to='images/bukti_payments', blank=True)
    status = models.CharField(max_length=20, choices = status_choices, default= 'pending')
    note = models.TextField(blank = True)
    created_date = models.DateTimeField(
        default = timezone.now
    )
    saldo = AdministrasiManager()
    objects = models.Manager() # The default manager.
    class Meta:
        ordering =['-created_date',]
    def __str__(self):
        return self.jenis.paymentstype

class Inventory(models.Model):
    thingsname = models.CharField(max_length=40)
    stock = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    detail = models.CharField(max_length=100)
    created_date = models.DateTimeField(
        default = timezone.now
    )
    updated_date = models.DateTimeField(
        blank = True, null = True
    )
    def update(self):
        self.updated_date = timezone.now()
        self.save()

class Meeting(models.Model):
    title = models.CharField(max_length=40)
    place = models.CharField(max_length=100, null=True, blank=True)
    date_meet = models.DateField(blank=True, null=True)
    user = models.ManyToManyField(User, related_name= "user_meeting_attendances", blank=True)
    note = models.TextField()
    created_date = models.DateField(
        default = timezone.now
    )
    updated_date = models.DateField(
        default = timezone.now
    )

templates/manajemen/absensi.html
{% extends 'manajemen/base.html' %}
{% block title%}
<h1>Absensi <h3>{{practice.date}}</h3></h1>
{% endblock %}

{% block content %}
ini list member
{% for users in  %}
<div>{{users.username}}</div>
{% endfor %}
{% endblock %}

templates/manajemen/acara.html
{% extends 'manajemen/base.html' %}
{% block title%}
Acara
{% endblock %}
{% block page_title %}
<!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
          <div class="col-sm-12 wow fadeIn">
            <i class="glyphicon glyphicon-sunglasses"></i>
            <h1><a href="{% url 'manajemen:home_acara' %}">Program </a>/ Hallo {{request.user.username}} !</h1>
          </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<br/>
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h3>Daftar Acara{% if user.is_authenticated %} ~<small>
          <a href="{%	url	'manajemen:new_event'	%}"> Tambah Baru</a>
      </small>{% endif %}</h3>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <table id="acara" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
          <thead>
              <tr>
                  <th>Nama Event</th>
                  <th>Perusahaan</th>
                  <th>Tanggal Acara</th>
                  <th>Status</th>
                  <th>Aksi</th>
              </tr>
          </thead>
          <tbody>
              {% for event in acaras %}
              <tr>
                  <td>{{event.event_name|slice:":20"}}..</td>
                  <td>{{event.corporate}}</td>
                  <td>{{event.event_date}}</td>
                  <th>{{event.event_status}}</th>
                  <td>
                    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModalDetail{{event.id}}"><span	class="fa fa-folder"></span> Lihat</button>
                    {% if event.event_status == "waiting" %}
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModalConfirm{{event.id}}"><i class="fa fa-check"></i> Konfirmasi</button>
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModalCancelled{{event.id}}"><i class="fa fa-times"></i> Batalkan</button>
                    {% elif event.event_status == "deal"  %}
                    <a class="btn	btn-warning btn-sm" href="{%	url	'manajemen:edit_event'	event.id	%}"><span	class="glyphicon	glyphicon-pencil"></span> Ubah</a>
                    {% else %}
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModalHapusEvent{{event.id}}"><span	class="glyphicon	glyphicon-trash"></span> Hapus</button>
                    {% endif %}
                  </td>
              </tr>
              <!-- Modal Confirm-->
              <div id="myModalConfirm{{event.id}}" class="modal fade" role="dialog">
                <div class="modal-dialog">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Konfirmasi "{{event.event_name}}" oleh-"{{event.sender}}"</h4>
                    </div>
                    <div class="modal-body center">
                      <p>Apakah Anda yakin untuk menerima penawaran<h3>{{event.event_name}}</h3> oleh saudara
                      <h4>{{event.sender}} ? </h4></p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                      <a href="{% url 'manajemen:confirmation_event' event.id %}"><button type="button" class="btn btn-primary">Ya</button></a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Modal Cencelled-->
              <div id="myModalCancelled{{event.id}}" class="modal fade" role="dialog">
                <div class="modal-dialog">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Tolak Tawaran Acara</h4>
                    </div>
                    <div class="modal-body center">
                      <p>Apakah Anda yakin untuk menolak acara <h3>{{event.event_name}}</h3> yang ditawarkan oleh
                      <h4>{{event.sender}}</h4> ? </p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                      <a href="{% url 'manajemen:cancel_event' event.id %}"><button type="button" class="btn btn-danger">Ya</button></a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Modal Details-->
              <div id="myModalDetail{{event.id}}" class="modal fade" role="dialog">
                <div class="modal-dialog">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Detail Acara -"{{event.event_name}}"</h4>
                    </div>
                    <div class="modal-body">
                      <div class = "col-md-4">
                        <b>Perusahaan Pengirim</b>
                      </div>
                      <div class = "col-md-8">{{event.corporate}}</div>
                      <div class = "clearfix"></div>
                      <br/>
                      <div class = "col-md-12">
                      {% if event.image %}
                        <img src="{{event.image.url}}">
                      {% endif %}
                      </div>
                      <br/>
                      <div class = "col-md-12">
                        <b>Deskripsi</b>
                      </div>
                      <br/>
                      <div class = "col-md-12">
                        {{event.desc}}
                      </div>
                      <div class = "clearfix"></div>
                      <br/>
                      <div class = "col-md-4">
                        <b>Tautan</b>
                      </div>
                      <div class = "col-md-8">
                        {% if event.attachment %}
                        {{event.attachment}}
                        {% else %}
                        -Tidak ada Tautan-
                        {% endif %}
                      </div>
                      <div class = "clearfix"></div>
                      <br/>
                      <div class = "col-md-4">
                        <b>Tanggal Acara</b>
                      </div>
                      <div class = "col-md-8">{{event.event_date}}</div>
                      <div class = "clearfix"></div>
                      <br/>
                      <div class = "col-md-12">
                        <p>Oleh {{event.sender}} - {{event.phone}}</p>
                      </div>
                      <div class = "col-md-12 center">
                        <h3>{{event.event_status}}</h3></div>
                      <div class = "clearfix"></div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Modal Hapus-->
              <div id="myModalHapusEvent{{event.id}}" class="modal fade" role="dialog">
                  <div class="modal-dialog">
                      <!-- Modal content-->
                      <div class="modal-content">
                          <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal">&times;</button>
                              <h4 class="modal-title">Hapus Acara - {{event.event_name}}</h4>
                          </div>
                          <div class="modal-body center">
                              <p>Apakah Anda yakin untuk menghapus Acara <b>{{event.event_name}}</b></p>
                                  <h3>{{event.event_date}} </h3>
                                  <small>oleh <b>{{event.corporate}}</small></b></p>
                          </div>
                          <div class="modal-footer">
                              <a href="{% url 'manajemen:delete_event' event.id %}"><button type="button" class="btn btn-danger">Delete</button></a>
                              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                          </div>
                      </div>
                  </div>
              </div>
              {% endfor %}
          </tbody>
      </table>
    </div>
  </div>
</div>
{% block script %}
<script>
$('#acara').DataTable({
  "ordering":false,
  "ScrollX":true,
});
</script>
{% endblock %}

{% endblock %}

templates/manajemen/edit_attendance.html
{% extends 'manajemen/base.html' %}
{% load admin_static %}
{% load bootstrap3 %}
{% block title%}
  Ubah Absensi
{% endblock %}
{% block page_title %}
<!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
          <div class="col-sm-12 wow fadeIn">
            <i class="fa fa-edit"></i>
            <h1><a href="{% url 'manajemen:home_psdm' %}">PSDM</a> /</h1>
            <p>Ubah Absensi </p>
          </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class ="col-md-8">
  <br>
  <form method="POST"> {% csrf_token %}
    <div class="form-group">
      <label class="control-label left" for="id_nama_kelas">
        Tutor</label>
        <br><b>{{tutor}}</b>
      </div>
    {% bootstrap_form form_edit_absensi %}
    <button type="submit" class="save btn btn-primary">Simpan</button>
  </form>
</div>
{% endblock %}

templates/manajemen/edit_barang.html
{% extends 'manajemen/base.html' %}
{% load bootstrap3 %}
{% block title%}
Ubah Data Barang
{% endblock %}
{% block page_title %}
<!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
          <div class="col-sm-12 wow fadeIn">
            <i class="fa fa-dropbox"></i>
            <h1><a href="{% url 'manajemen:home_inventaris' %}">Inventaris </a>/</h1>
            <p> Ubah Data Barang</p>
          </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class ="col-md-8 col-xs-12">
  <br>

  <form method="POST">
  <div class='left'><strong>Nama Barang</strong> <p><i>{{stuff_name}}</i></p></div>
    {% csrf_token %}
    {% bootstrap_form form_edit_barang %}
    <button class = "btn btn-primary" type="submit" class="save btn btn-default">Simpan</button>
  </form>
</div>
{% endblock %}

templates/manajemen/edit_class-nope.html
{% extends 'manajemen/base.html' %}
{% load admin_static %}
{% load bootstrap3 %}
{% block title%}
Ubah Kelas
{% endblock %}

{% block page_title %}
<!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
          <div class="col-sm-12 wow fadeIn">
            <i class="fa fa-pencil"></i>
            <h1><a href="{% url 'manajemen:home_psdm' %}">PSDM/</a></h1>
            <p>Ubah Kelas<i> Alliance Violin Community</i></p>
          </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class ="col-md-8">
  <br>
  <form method="POST"> {% csrf_token %}
    {% bootstrap_form form_edit_kelas %}
    <!-- <select class="select2_multiple form-control" multiple="multiple">
    </select-->
    <button class = "btn btn-primary" type="submit" class="save btn btn-default">Simpan</button>
  </form>
</div>
{% endblock %}

templates/manajemen/edit_main_article.html
{% extends 'manajemen/base.html' %}
{% load bootstrap3 %}
{% block title%}
Edit Main Article
{% endblock %}
{% block page_title %}
<!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
          <div class="col-sm-12 wow fadeIn">
            <i class="fa fa-pencil"></i>
            <h1><a href="{% url 'manajemen:home_hpd' %}">HPD /</a></h1>
            <p>Ubah Artikel <i> Alliance Violin Community</i></p>
          </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class ="col-md-8">
  <br>
  <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
    {% bootstrap_form form_main_edit_article %}
    <button class = "btn btn-primary" type="submit" class="save btn btn-default">Simpan</button>
  </form>
</div>
{% endblock %}

templates/manajemen/edit_schedule.html
{% extends 'manajemen/base.html' %}
{% load admin_static bootstrap3%}
{% block title%}
Jadwal Latihan
{% endblock %}
{% block static_admin %}

<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>

<script type="text/javascript" src="/static/admin/js/core.js"></script>

<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


<script type="text/javascript" src="/static/admin/js/calendar.js"></script>


{% endblock %}
{% block page_title %}
<!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
          <div class="col-sm-12 wow fadeIn">
            <i class="fa fa-pencil"></i>
            <h1><a href="{% url 'manajemen:home_psdm' %}">PSDM</a>/</h1>
            <p>Jadwal</p>
          </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
{{form_edit_schedule.media}}
<div class= "col-md-4"></div>
<div class= "col-md-4">
  <form method="POST"> {% csrf_token %}
    {% bootstrap_form form_edit_schedule%}

    <button type="submit" class="save btn btn-primary">Simpan</button>

  </form>
</div>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
var $j= jQuery.noConflict();

$( document ).ready(function() {
  // $j( "#id_date" ).datepicker({dateFormat: 'yy-mm-dd'});
  // alert($j(".datetimeshortcuts").html());

  $(".datetimeshortcuts").first().remove();



} );

</script>

{% endblock %}

templates/manajemen/new_article.html
{% extends 'manajemen/base.html' %}
{% load bootstrap3 %}
{% block title%}
Artikel Baru
{% endblock %}
{% block page_title %}
<!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
          <div class="col-sm-12 wow fadeIn">
            <i class="fa fa-adjust"></i>
            <h1><a href="{% url 'manajemen:home_hpd' %}">HPD</a>/</h1>
            <p>Artikel Baru</p>
          </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class ="col-md-10">
  <br>
  <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
    {% bootstrap_form form_edit_article %}
    <button class = "btn btn-info" type="submit" class="save btn btn-default">Simpan</button>
  </form>
</div>
{% endblock %}

templates/manajemen/new_attendance.html
{% extends 'manajemen/base.html' %}
{% load admin_static %}
{% load bootstrap3 %}
{% block title%}
Absensi
{% endblock %}
{% block page_title %}
<!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
          <div class="col-sm-12 wow fadeIn">
            <i class="fa fa-plus"></i>
            <h1><a href="{% url 'manajemen:home_psdm' %}">PSDM</a>/</h1>
            <p> Absensi Baru<i> Alliance Violin Community</i></p>
          </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class= "col-md-4"></div>
<div class= "col-md-4">
  <h1>Absensi</h1>
  <form method="POST"> {% csrf_token %}
    {% bootstrap_form form_new_absensi %}
    <button type="submit" class="save btn btn-primary">Save</button>
  </form>
</div>
<script>
$( function() {
  $( "#id_daftar_orang_text" ).autocomplete({
    source: "/ajax_select/ajax_lookup/users"
  });

} );
</script>
{% endblock %}

templates/manajemen/new_attendance_people.html
{% extends 'manajemen/base.html' %}
{% load admin_static %}
{% load bootstrap3 %}
{% block title%}
Absensi
{% endblock %}

{% block content %}
<h1>Absensi</h1>
<form method="POST"> {% csrf_token %}
  <div class="form-group">
    <label class="control-label left" for="id_nama_kelas">
      Tutor</label>
      <br><b>{{tutor}}</b>
    </div>
  {% bootstrap_form form_absensi_people %}
  <button type="submit" class="save btn btn-primary">Simpan</button>
</form>
{% endblock %}

templates/manajemen/new_class.html
{% extends 'manajemen/base.html' %}
{% load admin_static %}
{% load bootstrap3 %}
{% block title%}
Buat Kelas Baru
{% endblock %}
{% block page_title %}
<!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
          <div class="col-sm-12 wow fadeIn">
            <i class="fa fa-pencil"></i>
            <h1><a href="{% url 'manajemen:home_psdm' %}">PSDM</a></h1>
            <p>Buat Kelas Baru<i> Alliance Violin Community</i></p>
          </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class ="col-md-8">
  <br>
  <form method="POST"> {% csrf_token %}
    {% bootstrap_form form_new_kelas %}
    <button class = "btn btn-info" type="submit" class="save btn btn-default">Save</button>
  </form>
</div>
{% endblock %}